// Curated list of popular verses for "Verse of the Day" with English (King James Version - KJV) and Portuguese translations
export interface DailyVerseEntry {
  abbrev: string;
  chapter: number;
  verse: number;
  text?: string;
  textEn?: string;
  reference: string;
  referenceEn?: string;
}

const curatedVerses: DailyVerseEntry[] = [
  {
    abbrev: "jo",
    chapter: 3,
    verse: 16,
    reference: "João 3:16",
    referenceEn: "John 3:16",
    text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.",
    textEn: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
  },
  {
    abbrev: "sl",
    chapter: 23,
    verse: 1,
    reference: "Salmos 23:1",
    referenceEn: "Psalms 23:1",
    text: "O Senhor é o meu pastor; nada me faltará.",
    textEn: "The LORD is my shepherd; I shall not want.",
  },
  {
    abbrev: "fp",
    chapter: 4,
    verse: 13,
    reference: "Filipenses 4:13",
    referenceEn: "Philippians 4:13",
    text: "Posso todas as coisas naquele que me fortalece.",
    textEn: "I can do all things through Christ which strengtheneth me.",
  },
  {
    abbrev: "jr",
    chapter: 29,
    verse: 11,
    reference: "Jeremias 29:11",
    referenceEn: "Jeremiah 29:11",
    text: "Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais.",
    textEn: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
  },
  {
    abbrev: "rm",
    chapter: 8,
    verse: 28,
    reference: "Romanos 8:28",
    referenceEn: "Romans 8:28",
    text: "E sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.",
    textEn: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
  },
  {
    abbrev: "is",
    chapter: 41,
    verse: 10,
    reference: "Isaías 41:10",
    referenceEn: "Isaiah 41:10",
    text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.",
    textEn: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
  },
  {
    abbrev: "pv",
    chapter: 3,
    verse: 5,
    reference: "Provérbios 3:5",
    referenceEn: "Proverbs 3:5",
    text: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.",
    textEn: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
  },
  {
    abbrev: "mt",
    chapter: 11,
    verse: 28,
    reference: "Mateus 11:28",
    referenceEn: "Matthew 11:28",
    text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.",
    textEn: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
  },
  {
    abbrev: "sl",
    chapter: 46,
    verse: 1,
    reference: "Salmos 46:1",
    referenceEn: "Psalms 46:1",
    text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.",
    textEn: "God is our refuge and strength, a very present help in trouble.",
  },
  {
    abbrev: "ef",
    chapter: 2,
    verse: 8,
    reference: "Efésios 2:8",
    referenceEn: "Ephesians 2:8",
    text: "Porque pela graça sois salvos, por meio da fé; e isso não vem de vós; é dom de Deus.",
    textEn: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.",
  },
  {
    abbrev: "sl",
    chapter: 119,
    verse: 105,
    reference: "Salmos 119:105",
    referenceEn: "Psalms 119:105",
    text: "Lâmpada para os meus pés é tua palavra e luz, para o meu caminho.",
    textEn: "Thy word is a lamp unto my feet, and a light unto my path.",
  },
  {
    abbrev: "is",
    chapter: 40,
    verse: 31,
    reference: "Isaías 40:31",
    referenceEn: "Isaiah 40:31",
    text: "Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.",
    textEn: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
  },
  {
    abbrev: "rm",
    chapter: 12,
    verse: 2,
    reference: "Romanos 12:2",
    referenceEn: "Romans 12:2",
    text: "E não vos conformeis com este século, mas transformai-vos pela renovação da vossa mente, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.",
    textEn: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
  },
  {
    abbrev: "tg",
    chapter: 1,
    verse: 5,
    reference: "Tiago 1:5",
    referenceEn: "James 1:5",
    text: "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada.",
    textEn: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
  },
  {
    abbrev: "sl",
    chapter: 27,
    verse: 1,
    reference: "Salmos 27:1",
    referenceEn: "Psalms 27:1",
    text: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?",
    textEn: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
  },
  {
    abbrev: "gl",
    chapter: 5,
    verse: 22,
    reference: "Gálatas 5:22",
    referenceEn: "Galatians 5:22",
    text: "Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fidelidade,",
    textEn: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,",
  },
  {
    abbrev: "1co",
    chapter: 13,
    verse: 4,
    reference: "1 Coríntios 13:4",
    referenceEn: "1 Corinthians 13:4",
    text: "O amor é paciente, é benigno; o amor não arde em ciúmes, não se ufana, não se ensoberbece,",
    textEn: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,",
  },
  {
    abbrev: "hb",
    chapter: 11,
    verse: 1,
    reference: "Hebreus 11:1",
    referenceEn: "Hebrews 11:1",
    text: "Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem.",
    textEn: "Now faith is the substance of things hoped for, the evidence of things not seen.",
  },
  {
    abbrev: "sl",
    chapter: 37,
    verse: 4,
    reference: "Salmos 37:4",
    referenceEn: "Psalms 37:4",
    text: "Deleita-te também no Senhor, e ele te concederá os desejos do teu coração.",
    textEn: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.",
  },
  {
    abbrev: "2tm",
    chapter: 1,
    verse: 7,
    reference: "2 Timóteo 1:7",
    referenceEn: "2 Timothy 1:7",
    text: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.",
    textEn: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
  },
  {
    abbrev: "mt",
    chapter: 6,
    verse: 33,
    reference: "Mateus 6:33",
    referenceEn: "Matthew 6:33",
    text: "Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas.",
    textEn: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
  },
  {
    abbrev: "jo",
    chapter: 14,
    verse: 27,
    reference: "João 14:27",
    referenceEn: "John 14:27",
    text: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.",
    textEn: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
  },
  {
    abbrev: "sl",
    chapter: 91,
    verse: 1,
    reference: "Salmos 91:1",
    referenceEn: "Psalms 91:1",
    text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.",
    textEn: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.",
  },
  {
    abbrev: "1pe",
    chapter: 5,
    verse: 7,
    reference: "1 Pedro 5:7",
    referenceEn: "1 Peter 5:7",
    text: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.",
    textEn: "Casting all your care upon him; for he careth for you.",
  },
  {
    abbrev: "pv",
    chapter: 18,
    verse: 10,
    reference: "Provérbios 18:10",
    referenceEn: "Proverbs 18:10",
    text: "Torre forte é o nome do Senhor; para ela corre o justo e está em segurança.",
    textEn: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.",
  },
  {
    abbrev: "rm",
    chapter: 15,
    verse: 13,
    reference: "Romanos 15:13",
    referenceEn: "Romans 15:13",
    text: "O Deus de esperança vos encha de todo o gozo e paz no vosso crer, para que abundeis na esperança pelo poder do Espírito Santo.",
    textEn: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
  },
  {
    abbrev: "jo",
    chapter: 16,
    verse: 33,
    reference: "João 16:33",
    referenceEn: "John 16:33",
    text: "Tenho-vos dito estas coisas para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.",
    textEn: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
  },
  {
    abbrev: "sl",
    chapter: 34,
    verse: 8,
    reference: "Salmos 34:8",
    referenceEn: "Psalms 34:8",
    text: "Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.",
    textEn: "O taste and see that the LORD is good: blessed is the man that trusteth in him.",
  },
  {
    abbrev: "is",
    chapter: 26,
    verse: 3,
    reference: "Isaías 26:3",
    referenceEn: "Isaiah 26:3",
    text: "Tu conservarás em perfeita paz aquele cuja mente está firme em ti; porque ele confia em ti.",
    textEn: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
  },
  {
    abbrev: "cl",
    chapter: 3,
    verse: 23,
    reference: "Colossenses 3:23",
    referenceEn: "Colossians 3:23",
    text: "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens,",
    textEn: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;",
  },
  {
    abbrev: "sl",
    chapter: 121,
    verse: 1,
    reference: "Salmos 121:1",
    referenceEn: "Psalms 121:1",
    text: "Levantarei os meus olhos para os montes, de onde vem o meu socorro.",
    textEn: "I will lift up mine eyes unto the hills, from whence cometh my help.",
  },
];

export function getDailyVerseReference(): DailyVerseEntry {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000
  );
  return curatedVerses[dayOfYear % curatedVerses.length];
}


