export interface DailyVerse {
  id: number;
  text: string;
  reference: string;
}

export const dailyVerses: DailyVerse[] = [
  { id: 1, text: "O SENHOR é o meu pastor; nada me faltará.", reference: "Salmos 23:1" },
  { id: 2, text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.", reference: "João 3:16" },
  { id: 3, text: "Tudo posso naquele que me fortalece.", reference: "Filipenses 4:13" },
  { id: 4, text: "Se Deus é por nós, quem será contra nós?", reference: "Romanos 8:31" },
  { id: 5, text: "Lancem sobre ele todas as suas ansiedades, porque ele cuida de vocês.", reference: "1 Pedro 5:7" },
  { id: 6, text: "Busquem em primeiro lugar o Reino de Deus e a sua justiça, e todas estas coisas lhes serão acrescentadas.", reference: "Mateus 6:33" },
  { id: 7, text: "Não fui eu que lhe ordenei? Seja forte e corajoso! Não tenha medo, nem desanime, pois o SENHOR, seu Deus, estará com você por onde quer que você andar.", reference: "Josué 1:9" },
  { id: 8, text: "Confie no SENHOR de todo o seu coração, e não se apoie em seu próprio entendimento.", reference: "Provérbios 3:5" },
  { id: 9, text: "Mil poderão cair ao seu lado, e dez mil à sua direita, mas você não será atingido.", reference: "Salmos 91:7" },
  { id: 10, text: "E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.", reference: "Romanos 8:28" },
  { id: 11, text: "Não fiquem ansiosos por coisa alguma; antes, as suas petições sejam conhecidas diante de Deus em toda oração e súplica, com ação de graças.", reference: "Filipenses 4:6" },
  { id: 12, text: "E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.", reference: "Filipenses 4:7" },
  { id: 13, text: "O SENHOR é a minha luz e a minha salvação; de quem terei medo? O SENHOR é a fortaleza da minha vida; de quem terei temor?", reference: "Salmos 27:1" },
  { id: 14, text: "A vossa palavra seja sempre agradável, temperada com sal, para que saibais como deveis responder a cada um.", reference: "Colossenses 4:6" },
  { id: 15, text: "Porque sou eu que conheço os planos que tenho para vocês, diz o SENHOR, planos de paz e não de mal, para lhes dar um futuro e uma esperança.", reference: "Jeremias 29:11" },
  { id: 16, text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", reference: "1 Coríntios 13:4" },
  { id: 17, text: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.", reference: "Salmos 119:105" },
  { id: 18, text: "Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai, senão por mim.", reference: "João 14:6" },
  { id: 19, text: "Fiz o meu clamor ao SENHOR, e ele me respondeu; livrou-me de todos os meus temores.", reference: "Salmos 34:4" },
  { id: 20, text: "Mas os que esperam no SENHOR renovarão as suas forças; subirão com asas como águias; correrão e não se cansarão; caminharão e não se fatigarão.", reference: "Isaías 40:31" },
  { id: 21, text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", reference: "Mateus 11:28" },
  { id: 22, text: "O SENHOR está perto dos que têm o coração quebrantado, e salva os de espírito abatido.", reference: "Salmos 34:18" },
  { id: 23, text: "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.", reference: "Romanos 12:12" },
  { id: 24, text: "Instrua a criança no caminho em que deve andar, e, mesmo quando envelhecer, não se desviará dele.", reference: "Provérbios 22:6" },
  { id: 25, text: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.", reference: "João 14:27" },
  { id: 26, text: "A resposta branda desvia o furor, mas a palavra dura suscita a ira.", reference: "Provérbios 15:1" },
  { id: 27, text: "Eis que Deus é a minha salvação; confiarei e não temerei, porque o SENHOR Deus é a minha força e o meu cântico.", reference: "Isaías 12:2" },
  { id: 28, text: "Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus.", reference: "Romanos 8:1" },
  { id: 29, text: "Deleite-se no SENHOR, e ele lhe concederá os desejos do seu coração.", reference: "Salmos 37:4" },
  { id: 30, text: "O coração do homem traça o seu caminho, mas o SENHOR estabelece os seus passos.", reference: "Provérbios 16:9" },
  { id: 31, text: "A graça do Senhor Jesus Cristo, o amor de Deus e a comunhão do Espírito Santo sejam com todos vocês.", reference: "2 Coríntios 13:14" },
  { id: 32, text: "Porque para Deus nada será impossível.", reference: "Lucas 1:37" },
  { id: 33, text: "Em tudo deem graças, porque esta é a vontade de Deus em Cristo Jesus para com vocês.", reference: "1 Tessalonicenses 5:18" },
  { id: 34, text: "Ensina-nos a contar os nossos dias, para que alcancemos um coração sábio.", reference: "Salmos 90:12" },
  { id: 35, text: "O que guarda a sua boca e a sua língua guarda a sua alma de angústias.", reference: "Provérbios 21:23" },
  { id: 36, text: "Pois vocês foram salvos pela graça, por meio da fé; e isto não vem de vocês, é dom de Deus.", reference: "Efésios 2:8" },
  { id: 37, text: "Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o SENHOR, teu Deus, te dá.", reference: "Êxodo 20:12" },
  { id: 38, text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", reference: "Salmos 91:1" },
  { id: 39, text: "Guardei a tua palavra no meu coração, para não pecar contra ti.", reference: "Salmos 119:11" },
  { id: 40, text: "Eu sou a videira, vós as videiras; quem permanece em mim, e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer.", reference: "João 15:5" },
  { id: 41, text: "Mas, sede cumpridores da palavra, e não apenas ouvintes, enganando-vos a vós mesmos.", reference: "Tiago 1:22" },
  { id: 42, text: "Bem-aventurados os limpos de coração, porque eles verão a Deus.", reference: "Mateus 5:8" },
  { id: 43, text: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.", reference: "Salmos 23:4" },
  { id: 44, text: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda injustiça.", reference: "1 João 1:9" },
  { id: 45, text: "Não se deixem vencer pelo mal, mas vençam o mal com o bem.", reference: "Romanos 12:21" },
  { id: 46, text: "O SENHOR pelejará por vós, e vós vos calareis.", reference: "Êxodo 14:14" },
  { id: 47, text: "Toda a Escritura é divinamente inspirada e proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça.", reference: "2 Timóteo 3:16" },
  { id: 48, text: "De que serve ao homem ganhar o mundo inteiro e perder a sua alma?", reference: "Marcos 8:36" },
  { id: 49, text: "Em paz me deitarei e dormirei, porque só tu, SENHOR, me fazes habitar em segurança.", reference: "Salmos 4:8" },
  { id: 50, text: "A verdade os libertará.", reference: "João 8:32" },
  { id: 51, text: "No amor não há medo, antes o perfeito amor lança fora o medo.", reference: "1 João 4:18" },
  { id: 52, text: "Como são belos sobre os montes os pés do que anuncia as boas-novas, que proclama a paz.", reference: "Isaías 52:7" },
  { id: 53, text: "Elevo os meus olhos para os montes; de onde me virá o socorro? O meu socorro vem do SENHOR, que fez o céu e a terra.", reference: "Salmos 121:1-2" },
  { id: 54, text: "O fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão, domínio próprio.", reference: "Gálatas 5:22-23" },
  { id: 55, text: "Melhor é um dia nos teus átrios do que mil em outro lugar.", reference: "Salmos 84:10" },
  { id: 56, text: "Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta se abrirá para vocês.", reference: "Mateus 7:7" },
  { id: 57, text: "Mas a nossa pátria está nos céus, de onde também aguardamos o Salvador, o Senhor Jesus Cristo.", reference: "Filipenses 3:20" },
  { id: 58, text: "Criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou.", reference: "Gênesis 1:27" },
  { id: 59, text: "Não se cansem de fazer o bem, pois no tempo certo colheremos, se não desanimarmos.", reference: "Gálatas 6:9" },
  { id: 60, text: "Combati o bom combate, acabei a carreira, guardei a fé.", reference: "2 Timóteo 4:7" },
  { id: 61, text: "Porque a palavra de Deus é viva e eficaz, e mais cortante do que qualquer espada de dois gumes.", reference: "Hebreus 4:12" },
  { id: 62, text: "Amados, amemo-nos uns aos outros, porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.", reference: "1 João 4:7" },
  { id: 63, text: "Deem graças ao SENHOR, porque ele é bom; porque a sua misericórdia dura para sempre.", reference: "Salmos 136:1" },
  { id: 64, text: "Portanto, amem os seus inimigos e orem pelos que perseguem vocês.", reference: "Mateus 5:44" },
  { id: 65, text: "Sejam fortes e corajosos; não tenham medo nem fiquem apavorados diante deles, pois o SENHOR, seu Deus, vai com vocês; ele nunca os deixará, nunca os abandonará.", reference: "Deuteronômio 31:6" },
  { id: 66, text: "Provai e vede que o SENHOR é bom; bem-aventurado o homem que nele confia.", reference: "Salmos 34:8" },
  { id: 67, text: "Consagre ao SENHOR tudo o que você faz, e os seus planos serão bem-sucedidos.", reference: "Provérbios 16:3" },
  { id: 68, text: "Porventura não se vendem dois passarinhos por uma moedinha? Contudo, nenhum deles cairá no chão sem o consentimento do vosso Pai.", reference: "Mateus 10:29" },
  { id: 69, text: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente.", reference: "Romanos 12:2" },
  { id: 70, text: "A bênção do SENHOR traz riqueza, e ele não acrescenta dores a ela.", reference: "Provérbios 10:22" },
  { id: 71, text: "O SENHOR é a minha força e o meu escudo; nele o meu coração confiou, e fui socorrido.", reference: "Salmos 28:7" },
  { id: 72, text: "Ora, a foi é a certeza de coisas que se esperam, a convicção de fatos que não se veem.", reference: "Hebreus 11:1" },
  { id: 73, text: "Fomos sepultados com ele na morte pelo batismo, para que, como Cristo ressuscitou dos mortos pela glória do Pai, assim andemos nós também em novidade de vida.", reference: "Romanos 6:4" },
  { id: 74, text: "Portanto, confessem os seus pecados uns aos outros e orem uns pelos outros para serem curados. A oração fervorosa de um justo tem grande poder.", reference: "Tiago 5:16" },
  { id: 75, text: "Sede vós, pois, perfeitos, como é perfeito o vosso Pai que está nos céus.", reference: "Mateus 5:48" },
  { id: 76, text: "O SENHOR guardará a tua saída e a tua entrada, desde agora e para sempre.", reference: "Salmos 121:8" },
  { id: 77, text: "Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança nem sombra de variação.", reference: "Tiago 1:17" },
  { id: 78, text: "O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia.", reference: "Provérbios 28:13" },
  { id: 79, text: "Mas aquele que perseverar até o fim, esse será salvo.", reference: "Mateus 24:13" },
  { id: 80, text: "Quem poupa a vara odeia seu filho, mas quem o ama castiga-o logo.", reference: "Provérbios 13:24" },
  { id: 81, text: "A soberba precede a destruição, e a altivez do espírito precede a queda.", reference: "Provérbios 16:18" },
  { id: 82, text: "Eu te invoquei, ó Deus, pois tu me ouvirás; inclina para mim os teus ouvidos, e escuta as minhas palavras.", reference: "Salmos 17:6" },
  { id: 83, text: "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.", reference: "Romanos 6:23" },
  { id: 84, text: "Justificados, pois, mediante a fé, temos paz com Deus por meio de nosso Senhor Jesus Cristo.", reference: "Romanos 5:1" },
  { id: 85, text: "Sejam bondosos e compassivos uns para com os outros, perdoando-se mutuamente, assim como Deus os perdoou em Cristo.", reference: "Efésios 4:32" },
  { id: 86, text: "O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus.", reference: "Filipenses 4:19" },
  { id: 87, text: "Preciosa é aos olhos do SENHOR a morte dos seus santos.", reference: "Salmos 116:15" },
  { id: 88, text: "E, acima de tudo, tenham amor intenso uns para com os outros, porque o amor cobre uma multidão de pecados.", reference: "1 Pedro 4:8" },
  { id: 89, text: "A vossa moderação seja conhecida de todos os homens. Perto está o Senhor.", reference: "Filipenses 4:5" },
  { id: 90, text: "A esperança que se vê não é esperança; afinal, por que alguém ainda espera o que já vê? Mas, se esperamos o que não vemos, com paciência esperamos.", reference: "Romanos 8:24-25" },
  { id: 91, text: "Fui moço, e agora sou velho; contudo nunca vi desamparado o justo, nem a sua descendência a mendigar o pão.", reference: "Salmos 37:25" },
  { id: 92, text: "Portanto, deem a cada um o que lhe é devido: a quem imposto, imposto; a quem tributo, tributo; a quem temor, temor; a quem honra, honra.", reference: "Romanos 13:7" },
  { id: 93, text: "Ensina-me a fazer a tua vontade, pois tu és o meu Deus; guie-me o teu bom Espírito por terra plana.", reference: "Salmos 143:10" },
  { id: 94, text: "Porque todos pecaram e destituídos estão da glória de Deus.", reference: "Romanos 3:23" },
  { id: 95, text: "Mas Deus prova o seu amor para conosco, em que Cristo morreu por nós, sendo nós ainda pecadores.", reference: "Romanos 5:8" },
  { id: 96, text: "Para trás de mim, Satanás! Porque está escrito: Adorarás ao Senhor teu Deus, e só a ele servirás.", reference: "Lucas 4:8" },
  { id: 97, text: "Porque as armas da nossa milícia não são carnais, mas sim poderosas em Deus para destruição de fortalezas.", reference: "2 Coríntios 10:4" },
  { id: 98, text: "Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece os meus pensamentos.", reference: "Salmos 139:23" },
  { id: 99, text: "No mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.", reference: "João 16:33" },
  { id: 100, text: "A graça do Senhor Jesus seja com todos. Amém.", reference: "Apocalipse 22:21" }
];
