import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Nav
    "nav_home": "Início",
    "nav_search": "Buscar",
    "nav_ai": "IA",
    "nav_favorites": "Reações",
    "nav_devotional": "Devocionais e Planos",
    "nav_create": "Criar",
    "nav_account": "Conta",
    // User Role Badges
    "role_admin": "Conta Administrador",
    "role_beta": "Conta Beta",
    "role_standard": "Conta Padrão",
    // Presentation / Pulpit Mode
    "present": "Apresentar",
    "present_mode": "Modo Apresentação",
    "present_desc": "Apresentar versículos em tela cheia (Exclusivo Programa Beta)",
    "present_options": "Opções de Apresentação",
    "present_exit": "Sair da Apresentação",
    "present_exit_esc": "Sair da Apresentação (Esc)",
    "present_fullscreen": "Tela Cheia (F)",
    "present_exit_fullscreen": "Sair da Tela Cheia (F)",
    "present_verse_of": "Versículo",
    "present_of": "de",
    "present_change_book_chapter": "Trocar Livro ou Capítulo",
    "present_font_size": "Tamanho da Fonte",
    "present_screen_theme": "Tema do Telão",
    "present_theme_app": "Tema do App",
    "present_theme_dark": "Obsidiana / Preto Puro",
    "present_theme_gold": "Dourado Nobre",
    "present_theme_emerald": "Esmeralda Sagrado",
    "present_select_book_chapter": "Selecionar Livro e Capítulo",
    "present_select_chapter": "Selecione o Capítulo:",
    "present_current_chapter": "Capítulo atual:",
    "present_prev_verse": "Versículo anterior",
    "present_next_verse": "Próximo versículo",
    "present_smooth_transition": "Transição Suave",
    "present_auto_speed": "Velocidade de Reprodução Automática",
    // Reader & Bilingual
    "bilingual": "Bilíngue",
    "bilingual_translating": "Traduzindo com IA...",
    "bilingual_active": "Tradução IA ativa",
    "bilingual_login_needed": "Faça login para usar o modo bilíngue",
    "bilingual_limit_title": "Limite do Modo Bilíngue Atingido",
    "bilingual_limit_desc": "Você atingiu o limite de 3 capítulos traduzidos por dia no modo gratuito. Sua cota recarrega em 12 horas.",
    "bilingual_realtime": "Traduzindo versículos em tempo real (blocos de 5)...",
    "bilingual_translating_verse": "Traduzindo versículo...",
    // Dictionary
    "dictionary": "Dicionário",
    "dictionary_login_needed": "Faça login para usar o dicionário",
    "dictionary_ai_badge": "Dicionário Bíblico IA",
    "dictionary_ai_sub": "IA com auxílio de erudição bíblica",
    "dictionary_analyzing": "Analisando versículo e contexto histórico...",
    "dictionary_limit_title": "Limite do Dicionário Atingido",
    "dictionary_limit_desc": "Você atingiu o limite de 3 consultas ao Dicionário por dia no modo gratuito. Cota recarrega em 12 horas.",
    // Reader General
    "books": "Livros",
    "book_not_found": "Livro não encontrado.",
    "save": "Salvar",
    "cancel": "Cancelar",
    "write_note": "Escreva sua anotação... (máx. 1000 caracteres)",
    "create_image_count": "Criar imagem",
    "share_text": "Compartilhar texto",
    "offline_mode_title": "Modo Offline",
    "offline_mode_desc": "Sem conexão e sem dados offline baixados. Para ler sem internet, baixe a Bíblia.",
    "download_offline_bible": "Baixar Bíblia Offline",
    "load_more_verses": "Carregando mais versículos de forma incremental... ou clique para exibir mais",
    "chapter_abbrev": "Cap.",
    "chapter_short": "Cap.",
    // Font Size & Audio Speech Reader
    "font_size_btn": "Tamanho da Fonte",
    "font_size_sm": "Pequena (14px)",
    "font_size_md": "Padrão (16px)",
    "font_size_lg": "Grande (18px)",
    "font_size_xl": "Extra Grande (22px)",
    "font_size_2xl": "Gigante (26px)",
    "audio_reader_btn": "Leitura Falada",
    "audio_reader_playing": "Lendo Capítulo em Áudio...",
    "audio_reader_paused": "Áudio Pausado",
    "audio_reader_stopped": "Leitura em Áudio Parada",
    "audio_reader_unsupported": "Seu navegador não suporta síntese de voz (TTS).",
    "audio_verse_label": "Versículo Atual:",
    "audio_speed_label": "Velocidade:",
    "maps_biblical_title": "Mapas Bíblicos",
    "maps_biblical_sub": "Geografia e Rotas Históricas das Escrituras",
    // Home / Index
    "hero_subtitle": "Leia a Palavra, estude com a IA Bíblica e transforme versículos em arte. Tudo em um só lugar.",
    "created_by": "Criado por Mundo Gospel",
    "subscribe": "Inscreva-se",
    "verse_of_the_day": "Versículo do Dia",
    "thousands_verses": "+ de 1.000 Versículos Sagrados",
    "thousands_verses_sub": "Mais de 31.000 versículos e 66 Livros Sagrados",
    "thousands_verses_desc": "Navegação offline instantânea, comparações de traduções e estudos em qualquer capítulo da Bíblia.",
    "start_reading_genesis": "Começar Leitura (Gênesis 1)",
    "ai_dictionary_title": "Dicionário e IA Bíblica",
    "ai_dictionary_sub": "Estudo Aprofundado e Dicionário Teológico IA",
    "ai_dictionary_desc": "Esclareça contextos históricos, palavras originais em hebraico/grego e significados práticos para cada versículo.",
    "access_ai": "Acessar Inteligência Artificial Bíblica",
    "create_page_verse": "Criar página com este versículo",
    "old_testament": "Antigo Testamento",
    "new_testament": "Novo Testamento",
    "chapters_count": "cap.",
    "all_rights_reserved": "© 2026 Biblia Online. Todos os direitos reservados.",
    "terms_privacy": "Termos de Uso e Política de Privacidade",
    // Cookies & LGPD
    "cookies_title": "Privacidade e Cookies (LGPD)",
    "cookies_desc": "Visando a máxima transparência e conformidade legal, informamos que utilizamos cookies para oferecer uma experiência personalizada, otimizar a navegação e analisar o tráfego do site. Respeitamos os seus direitos conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018) e garantimos a você o total controle sobre as suas preferências de privacidade.",
    "cookies_accept_all": "Aceitar Todos",
    "cookies_reject_non_essential": "Rejeitar Não-Essenciais",
    "cookies_configure": "Configurar",
    "cookies_customize": "Personalizar",
    "cookies_save": "Salvar Preferências",
    "cookies_essential": "Essenciais",
    "cookies_essential_desc": "Necessários para o funcionamento",
    "cookies_analytics": "Análise e Performance",
    "cookies_analytics_desc": "Melhoram nossa entrega",
    "cookies_personalization": "Funcionais",
    "cookies_personalization_desc": "Lembram suas preferências",
    // Account Settings Page
    "settings_title": "Configurações",
    "language_title": "Idioma",
    "language_sub": "Idioma do aplicativo",
    "language_pt": "Português",
    "language_en": "Inglês",
    "notifications_title": "Notificações",
    "notifications_desc_active": "Mensagens Diárias (8h e 20h)",
    "notifications_desc_inactive": "Desativadas",
    "focus_title": "Foco",
    "focus_badge_timer": "Timer de 1 hora",
    "focus_desc_active": "Ativado — toasts normais silenciados para focar na Palavra",
    "focus_desc_inactive": "Desativa toasts normais para focar na Palavra (1h de timer)",
    "focus_time_remaining": "Tempo restante de foco:",
    "focus_renew": "Renovar 1h",
    "focus_turn_off": "Desativar",
    "test_now": "Testar Agora",
    "clock_status": "Status do Relógio:",
    "clock_active": "Ativo",
    "offline_title": "Bíblia Offline",
    "offline_desc_downloading": "Baixando...",
    "offline_desc_active": "Baixada — funciona sem internet",
    "offline_desc_inactive": "Baixar para usar offline",
    "delete_account": "Excluir Minha Conta e Dados",
    "delete_account_desc": "Apagar perfil e atividades permanentemente",
    "sign_out": "Sair da Conta",
    "add_name": "Adicionar nome",
    "your_name": "Seu nome",
    "not_supported": "Não suportado",
    "not_supported_desc": "Seu navegador não suporta notificações.",
    "permission_denied": "Permissão Negada",
    "permission_denied_desc": "Você precisa permitir notificações nas configurações do seu navegador para testar.",
    "notifications_blocked": "Notificações Bloqueadas",
    "notifications_blocked_desc": "Por favor, libere a permissão de notificações nas configurações do site no seu navegador.",
    "test_sent": "Teste enviado! 🔔",
    "test_sent_desc": "Você deve receber uma notificação em instantes.",
    "login_needed": "Faça login para salvar seu progresso e sincronizar seus dados.",
    "enter_account": "Entrar na Conta",
    "create_account": "Criar Conta",
    "deleting_profile": "Carregando...",
    "delete_modal_title": "Excluir Conta",
    "delete_modal_alert": "Alerta: ao excluir sua conta você apagará todos seus dados e não poderá recuperá-los. Além disso, você terá que aguardar um período de 30 dias para poder criar uma nova conta com este mesmo e-mail.",
    "delete_modal_confirm": "Apagar meus dados",
    "delete_modal_cancel": "Cancelar",
    // Offline AI
    "no_connection": "Sem Conexão",
    "no_internet_ai_desc": "Você precisa de internet para usar IA. Por favor, verifique sua conexão Wi-Fi ou dados móveis e tente novamente.",
    "try_again": "Tentar novamente",
    "no_internet_dict_desc": "Você precisa de internet para usar o Dicionário com IA",
    "no_internet_dict_sub": "Por favor, reconecte-se e tente novamente.",
    "no_internet_translation_desc": "Você precisa de internet para usar Tradução com IA",
    "no_internet_translation_sub": "O modo Bilíngue requer internet para traduzir dinamicamente os versículos via Inteligência Artificial.",
    "no_internet_create_desc": "Você precisa de internet para usar IA",
    "no_internet_create_sub": "O modo Criar com IA requer uma conexão ativa com a internet para gerar novos fundos baseados em versículos."
  },
  en: {
    // Nav
    "nav_home": "Home",
    "nav_search": "Search",
    "nav_ai": "AI",
    "nav_favorites": "Reactions",
    "nav_devotional": "Devotionals & Plans",
    "nav_create": "Create",
    "nav_account": "Account",
    // User Role Badges
    "role_admin": "Admin Account",
    "role_beta": "Beta Account",
    "role_standard": "Standard Account",
    // Presentation / Pulpit Mode
    "present": "Present",
    "present_mode": "Presentation Mode",
    "present_desc": "Present verses in full screen (Exclusive Beta Program)",
    "present_options": "Presentation Options",
    "present_exit": "Exit Presentation",
    "present_exit_esc": "Exit Presentation (Esc)",
    "present_fullscreen": "Fullscreen (F)",
    "present_exit_fullscreen": "Exit Fullscreen (F)",
    "present_verse_of": "Verse",
    "present_of": "of",
    "present_change_book_chapter": "Change Book or Chapter",
    "present_font_size": "Font Size",
    "present_screen_theme": "Screen Theme",
    "present_theme_app": "App Theme",
    "present_theme_dark": "Obsidian / Pure Black",
    "present_theme_gold": "Noble Gold",
    "present_theme_emerald": "Sacred Emerald",
    "present_select_book_chapter": "Select Book & Chapter",
    "present_select_chapter": "Select Chapter:",
    "present_current_chapter": "Current chapter:",
    "present_prev_verse": "Previous verse",
    "present_next_verse": "Next verse",
    "present_smooth_transition": "Smooth Transition",
    "present_auto_speed": "Auto-Playback Speed",
    // Reader & Bilingual
    "bilingual": "Bilingual",
    "bilingual_translating": "Translating with AI...",
    "bilingual_active": "AI Translation active",
    "bilingual_login_needed": "Please log in to use bilingual mode",
    "bilingual_limit_title": "Bilingual Mode Limit Reached",
    "bilingual_limit_desc": "You have reached the limit of 3 translated chapters per day in free mode. Quota resets in 12 hours.",
    "bilingual_realtime": "Translating verses in real-time (batches of 5)...",
    "bilingual_translating_verse": "Translating verse...",
    // Dictionary
    "dictionary": "Dictionary",
    "dictionary_login_needed": "Please log in to use dictionary",
    "dictionary_ai_badge": "Bible Dictionary AI",
    "dictionary_ai_sub": "AI powered by biblical scholarship",
    "dictionary_analyzing": "Analyzing verse and historical context...",
    "dictionary_limit_title": "Dictionary Limit Reached",
    "dictionary_limit_desc": "You have reached the limit of 3 Dictionary queries per day in free mode. Quota resets in 12 hours.",
    // Reader General
    "books": "Books",
    "book_not_found": "Book not found.",
    "save": "Save",
    "cancel": "Cancel",
    "write_note": "Write your note... (max. 1000 characters)",
    "create_image_count": "Create image",
    "share_text": "Share text",
    "offline_mode_title": "Offline Mode",
    "offline_mode_desc": "No connection and no offline data downloaded. To read without internet, download the Bible.",
    "download_offline_bible": "Download Offline Bible",
    "load_more_verses": "Loading more verses incrementally... or click to display more",
    "chapter_abbrev": "Ch.",
    "chapter_short": "Ch.",
    // Font Size & Audio Speech Reader
    "font_size_btn": "Font Size",
    "font_size_sm": "Small (14px)",
    "font_size_md": "Medium (16px)",
    "font_size_lg": "Large (18px)",
    "font_size_xl": "Extra Large (22px)",
    "font_size_2xl": "Huge (26px)",
    "audio_reader_btn": "Read Aloud",
    "audio_reader_playing": "Reading Chapter Aloud...",
    "audio_reader_paused": "Audio Paused",
    "audio_reader_stopped": "Audio Reading Stopped",
    "audio_reader_unsupported": "Your browser does not support text-to-speech synthesis (TTS).",
    "audio_verse_label": "Current Verse:",
    "audio_speed_label": "Speed:",
    "maps_biblical_title": "Biblical Maps",
    "maps_biblical_sub": "Geography and Historical Scripture Routes",
    // Home / Index
    "hero_subtitle": "Read the Word, study with Biblical AI, and transform verses into art. All in one place.",
    "created_by": "Created by Mundo Gospel",
    "subscribe": "Subscribe",
    "verse_of_the_day": "Verse of the Day",
    "thousands_verses": "+1,000 Sacred Verses",
    "thousands_verses_sub": "Over 31,000 verses and 66 Holy Books",
    "thousands_verses_desc": "Instant offline navigation, translation comparisons, and study across any chapter in the Bible.",
    "start_reading_genesis": "Start Reading (Genesis 1)",
    "ai_dictionary_title": "Dictionary & Biblical AI",
    "ai_dictionary_sub": "In-Depth Study & Theological AI Dictionary",
    "ai_dictionary_desc": "Clarify historical contexts, original Hebrew/Greek words, and practical applications for each verse.",
    "access_ai": "Access Biblical Artificial Intelligence",
    "create_page_verse": "Create page with this verse",
    "old_testament": "Old Testament",
    "new_testament": "New Testament",
    "chapters_count": "ch.",
    "all_rights_reserved": "© 2026 Biblia Online. All rights reserved.",
    "terms_privacy": "Terms of Use & Privacy Policy",
    // Cookies & LGPD
    "cookies_title": "Privacy & Cookies (LGPD/GDPR)",
    "cookies_desc": "To ensure transparency and compliance, we use cookies to personalize your experience, optimize navigation, and analyze site performance. We respect your rights and give you full control over your privacy settings.",
    "cookies_accept_all": "Accept All",
    "cookies_reject_non_essential": "Reject Non-Essential",
    "cookies_configure": "Configure",
    "cookies_customize": "Customize",
    "cookies_save": "Save Preferences",
    "cookies_essential": "Essential",
    "cookies_essential_desc": "Required for core functionality",
    "cookies_analytics": "Analytics & Performance",
    "cookies_analytics_desc": "Helps improve our services",
    "cookies_personalization": "Functional",
    "cookies_personalization_desc": "Remembers your preferences",
    // Account Settings Page
    "settings_title": "Settings",
    "language_title": "Language",
    "language_sub": "Application language",
    "language_pt": "Portuguese",
    "language_en": "English",
    "notifications_title": "Notifications",
    "notifications_desc_active": "Daily Messages (8am and 8pm)",
    "notifications_desc_inactive": "Disabled",
    "focus_title": "Focus",
    "focus_badge_timer": "1-hour timer",
    "focus_desc_active": "Active — normal toasts silenced to focus on the Word",
    "focus_desc_inactive": "Disables normal toasts to focus on the Word (1h timer)",
    "focus_time_remaining": "Focus time remaining:",
    "focus_renew": "Renew 1h",
    "focus_turn_off": "Turn Off",
    "test_now": "Test Now",
    "clock_status": "Clock Status:",
    "clock_active": "Active",
    "offline_title": "Offline Bible",
    "offline_desc_downloading": "Downloading...",
    "offline_desc_active": "Downloaded — works without internet",
    "offline_desc_inactive": "Download to use offline",
    "delete_account": "Delete My Account and Data",
    "delete_account_desc": "Permanently delete profile and activities",
    "sign_out": "Sign Out",
    "add_name": "Add name",
    "your_name": "Your name",
    "not_supported": "Not supported",
    "not_supported_desc": "Your browser does not support notifications.",
    "permission_denied": "Permission Denied",
    "permission_denied_desc": "You need to allow notifications in your browser settings to test.",
    "notifications_blocked": "Notifications Blocked",
    "notifications_blocked_desc": "Please enable notification permission in your browser's site settings.",
    "test_sent": "Test sent! 🔔",
    "test_sent_desc": "You should receive a notification in a moment.",
    "login_needed": "Log in to save your progress and sync your data.",
    "enter_account": "Sign In",
    "create_account": "Create Account",
    "deleting_profile": "Loading...",
    "delete_modal_title": "Delete Account",
    "delete_modal_alert": "Warning: deleting your account will erase all your data and cannot be recovered. Additionally, you will have to wait for a period of 30 days before being able to create a new account with this same email.",
    "delete_modal_confirm": "Delete my data",
    "delete_modal_cancel": "Cancel",
    // Offline AI
    "no_connection": "No Connection",
    "no_internet_ai_desc": "You need internet to use AI. Please check your Wi-Fi or mobile data connection and try again.",
    "try_again": "Try again",
    "no_internet_dict_desc": "You need internet to use Bible Dictionary AI",
    "no_internet_dict_sub": "Please reconnect and try again.",
    "no_internet_translation_desc": "You need internet to use AI Translation",
    "no_internet_translation_sub": "Bilingual mode requires internet to dynamically translate verses via Artificial Intelligence.",
    "no_internet_create_desc": "You need internet to use AI",
    "no_internet_create_sub": "Create with AI mode requires an active internet connection to generate new verse-based backgrounds."
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "pt",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved === "en" || saved === "pt") ? saved : "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["pt"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
