import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Nav
    "nav_home": "Início",
    "nav_search": "Buscar",
    "nav_ai": "IA",
    "nav_favorites": "Reações",
    "nav_devotional": "Devocionais e Planos",
    "nav_devotional_short": "Devocionais",
    "nav_create": "Criar",
    "nav_account": "Conta",
    // User Role Badges
    "role_admin": "Conta Administrador",
    "role_beta": "Conta Beta",
    "role_standard": "Conta Normal",
    // Presentation / Pulpit Mode
    "present": "Apresentar",
    "present_mode": "Modo Apresentação",
    "present_desc": "Apresentar versículos em tela cheia (Recurso em Testes)",
    "present_options": "Opções de Apresentação",
    "present_exit": "Sair da Apresentação",
    "present_exit_esc": "Sair da Apresentação (Esc)",
    "present_fullscreen": "Tela Cheia (F)",
    "present_exit_fullscreen": "Sair da Tela Cheia (F)",
    "present_verse_of": "Versículo",
    "present_of": "de",
    "present_change_book_chapter": "Trocar Livro ou Capítulo",
    "present_font_size": "Tamanho da Fonte",
    "present_screen_theme": "Tema do Telão",
    "present_theme_app": "Tema do App",
    "present_theme_dark": "Obsidiana / Preto Puro",
    "present_theme_gold": "Dourado Nobre",
    "present_theme_emerald": "Esmeralda Sagrado",
    "present_select_book_chapter": "Selecionar Livro e Capítulo",
    "present_select_chapter": "Selecione o Capítulo:",
    "present_current_chapter": "Capítulo atual:",
    "present_prev_verse": "Versículo anterior",
    "present_next_verse": "Próximo versículo",
    "present_smooth_transition": "Transição Suave",
    "present_auto_speed": "Velocidade de Reprodução Automática",
    // Reader e Bilingual
    "bilingual": "Bilíngue",
    "bilingual_translating": "Traduzindo com IA...",
    "bilingual_active": "Tradução IA ativa",
    "bilingual_login_needed": "Faça login para usar o modo bilíngue",
    "bilingual_limit_title": "Limite do Modo Bilíngue Atingido",
    "bilingual_limit_desc": "Você atingiu o limite de 3 capítulos traduzidos por dia no modo gratuito. Sua cota recarrega em 12 horas.",
    "bilingual_realtime": "Traduzindo versículos em tempo real (blocos de 5)...",
    "bilingual_translating_verse": "Traduzindo versículo...",
    // Dictionary
    "dictionary": "Dicionário",
    "dictionary_login_needed": "Faça login para usar o dicionário",
    "dictionary_ai_badge": "Dicionário Bíblico IA",
    "dictionary_ai_sub": "IA com auxílio de erudição bíblica",
    "dictionary_analyzing": "Analisando versículo e contexto histórico...",
    "dictionary_limit_title": "Limite do Dicionário Atingido",
    "dictionary_limit_desc": "Você atingiu o limite de 3 consultas ao Dicionário por dia no modo gratuito. Cota recarrega em 12 horas.",
    "dict_title": "Dicionário Bíblico IA",
    "dict_subtitle": "IA com auxílio de erudição bíblica",
    "dict_offline_title": "Modo Offline",
    "dict_offline_desc": "O Dicionário com IA requer conexão com a internet.",
    "dict_analyzing": "Analisando versículo e contexto histórico...",
    "dict_limit_title": "Limite do Dicionário Atingido",
    "dict_limit_desc": "Você atingiu o limite de 3 consultas ao Dicionário por dia no modo gratuito. Cota recarrega em 12 horas.",
    // Reader General
    "books": "Livros",
    "book_not_found": "Livro não encontrado.",
    "save": "Salvar",
    "cancel": "Cancelar",
    "write_note": "Escreva sua anotação... (máx. 1000 caracteres)",
    "note_placeholder": "Escreva sua anotação... (máx. 1000 caracteres)",
    "create_image_count": "Criar imagem",
    "create_image": "Criar imagem",
    "share_text": "Compartilhar texto",
    "offline_mode_title": "Modo Offline",
    "offline_mode_desc": "Sem conexão e sem dados offline baixados. Para ler sem internet, baixe a Bíblia.",
    "download_offline_bible": "Baixar Bíblia Offline",
    "load_more_verses": "Carregando mais versículos de forma incremental... ou clique para exibir mais",
    "loading_more_verses": "Carregando mais versículos de forma incremental... ou clique para exibir mais",
    "chapter_abbrev": "Cap.",
    "chapter_short": "Cap.",
    // Font Size e Audio Speech Reader
    "font_size_btn": "Tamanho da Fonte",
    "font_size_sm": "Pequena (14px)",
    "font_size_md": "Padrão (16px)",
    "font_size_lg": "Grande (18px)",
    "font_size_xl": "Extra Grande (22px)",
    "font_size_2xl": "Gigante (26px)",
    "audio_reader_btn": "Leitura Falada",
    "audio_reader_playing": "Lendo Capítulo em Áudio...",
    "audio_reader_paused": "Áudio Pausado",
    "audio_reader_stopped": "Leitura em Áudio Parada",
    "audio_reader_unsupported": "Seu navegador não suporta síntese de voz (TTS).",
    "audio_verse_label": "Versículo Atual:",
    "audio_speed_label": "Velocidade:",
    "maps_biblical_title": "Mapas Bíblicos",
    "maps_biblical_sub": "Geografia e Rotas Históricas das Escrituras",
    // Home / Index
    "hero_subtitle": "Leia a Palavra, estude com a IA Bíblica e transforme versículos em arte. Tudo em um só lugar.",
    "created_by": "Criado por Mundo Gospel",
    "subscribe": "Inscreva-se",
    "verse_of_the_day": "Versículo do Dia",
    "thousands_verses": "+ de 1.000 Versículos Sagrados",
    "thousands_verses_sub": "Mais de 31.000 versículos e 66 Livros Sagrados",
    "thousands_verses_desc": "Navegação offline instantânea, comparações de traduções e estudos em qualquer capítulo da Bíblia.",
    "start_reading_genesis": "Começar Leitura (Gênesis 1)",
    "ai_dictionary_title": "Dicionário e IA Bíblica",
    "ai_dictionary_sub": "Estudo Aprofundado e Dicionário Teológico IA",
    "ai_dictionary_desc": "Esclareça contextos históricos, palavras originais em hebraico/grego e significados práticos para cada versículo.",
    "access_ai": "Acessar Inteligência Artificial Bíblica",
    "create_page_verse": "Criar página com este versículo",
    "old_testament": "Antigo Testamento",
    "new_testament": "Novo Testamento",
    "chapters_count": "cap.",
    "all_rights_reserved": "© 2026 Biblia Online. Todos os direitos reservados.",
    "terms_privacy": "Termos de Uso e Política de Privacidade",
    // Devotionals e Plans Page
    "devotional_title": "Devocionais e Planos Diários",
    "devotional_subtitle": "Meditações diárias e planos de leitura estruturados para fortalecer sua fé a cada dia.",
    "tab_today_devotional": "Devocional de Hoje",
    "tab_reading_plans": "Planos de Leitura",
    "tab_biblical_maps": "Mapas Bíblicos",
    "tab_explore_devotionals": "Explorar Devocionais",
    "tab_my_favorites": "Meus Favoritos",
    "meditation_of_the_day": "Meditação do Dia",
    "changes_at_midnight": "Muda automaticamente à meia-noite",
    "theme_label": "Tema:",
    "reflection_title": "Reflexão",
    "today_prayer": "Oração para Hoje",
    "copy_devotional": "Copiar Devocional",
    "share_devotional": "Compartilhar Devocional",
    "copied": "Copiado!",
    "copy": "Copiar",
    "read_full_reflection": "Ler reflexão completa",
    "collapse_reflection": "Recolher",
    "recommended_prayer": "Oração recomendada",
    "filter_by_theme": "Filtrar por Tema",
    "search_devotionals_placeholder": "Pesquisar por título, versículo, referência ou reflexão...",
    "showing_devotionals_count": "Mostrando",
    "of_devotionals": "de",
    "devotionals_available": "devocionais disponíveis.",
    "no_devotionals_found": "Nenhum devocional corresponde aos critérios de pesquisa.",
    "clear_search_filters": "Limpar filtros de busca",
    "favorited_devotionals": "Devocionais Favoritados",
    "favorited_reading_plans": "Planos de Leitura Favoritados",
    "no_favorited_devotionals": "Nenhum devocional individual salvo nos favoritos ainda.",
    "no_favorited_plans": "Nenhum plano de leitura salvo nos favoritos ainda.",
    "go_to_plan": "Ir para o Plano",
    "days_unit": "Dias",
    "all_categories": "Todas",
    "plan_active_badge": "Plano Ativo",
    "plan_duration": "Duração",
    "plan_completed_badge": "Concluído!",
    "plan_start_btn": "Iniciar Plano",
    "plan_continue_btn": "Continuar Leitura",
    "plan_streak": "Sequência",
    "plan_days_done": "dias concluídos",
    "plan_day_label": "Dia",
    "plan_mark_completed": "Marcar como concluído",
    "plan_unmark": "Desmarcar",
    "plan_reflection_placeholder": "O que Deus falou com você hoje nesta leitura?",
    "plan_save_reflection": "Salvar Lição",
    "plan_reflection_saved": "Lição salva!",
    // Favorites e Reactions Page
    "reactions_title": "Reações e Favoritos",
    "reactions_subtitle": "Versículos guardados, marcações e suas anotações pessoais da Palavra.",
    "fav_tab_favorites": "Favoritos",
    "fav_tab_markings": "Marcações",
    "fav_tab_notes": "Anotações",
    "fav_title_favorites": "Versículos Favoritos",
    "fav_title_markings": "Marcações",
    "fav_title_notes": "Anotações",
    "fav_no_favorites": "Nenhum versículo favoritado ainda. Toque no ícone de coração nos capítulos para guardar seus versículos prediletos.",
    "fav_no_markings": "Nenhuma marcação salva ainda. Destaque versículos durante sua leitura bíblica.",
    "fav_no_notes": "Nenhuma anotação salva ainda. Escreva reflexões em qualquer versículo.",
    "fav_recommendations": "Recomendações",
    "fav_edit_note": "Editar anotação",
    "fav_save_note": "Salvar anotação",
    "fav_remove": "Remover",
    "fav_verse_copied": "Versículo copiado com sucesso",
    // Cookies e LGPD
    "cookie_title": "Privacidade e Cookies (LGPD)",
    "cookie_desc": "Visando a máxima transparência e conformidade legal, informamos que utilizamos cookies para oferecer uma experiência personalizada, otimizar a navegação e analisar o tráfego do site. Respeitamos os seus direitos conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018) e garantimos a você o total controle sobre as suas preferências de privacidade.",
    "cookie_accept_all": "Aceitar Todos",
    "cookie_reject_non_essential": "Rejeitar Não-Essenciais",
    "cookie_configure": "Configurar",
    "cookie_customize": "Personalizar",
    "cookie_save_preferences": "Salvar Preferências",
    "cookie_essential": "Essenciais",
    "cookie_essential_desc": "Necessários para o funcionamento",
    "cookie_analytics": "Análise e Performance",
    "cookie_analytics_desc": "Melhoram nossa entrega",
    "cookie_functional": "Funcionais",
    "cookie_functional_desc": "Lembram suas preferências",
    "cookies_title": "Privacidade e Cookies (LGPD)",
    "cookies_desc": "Visando a máxima transparência e conformidade legal, informamos que utilizamos cookies para oferecer uma experiência personalizada, otimizar a navegação e analisar o tráfego do site. Respeitamos os seus direitos conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018) e garantimos a você o total controle sobre as suas preferências de privacidade.",
    "cookies_accept_all": "Aceitar Todos",
    "cookies_reject_non_essential": "Rejeitar Não-Essenciais",
    "cookies_configure": "Configurar",
    "cookies_customize": "Personalizar",
    "cookies_save": "Salvar Preferências",
    "cookies_essential": "Essenciais",
    "cookies_essential_desc": "Necessários para o funcionamento",
    "cookies_analytics": "Análise e Performance",
    "cookies_analytics_desc": "Melhoram nossa entrega",
    "cookies_personalization": "Funcionais",
    "cookies_personalization_desc": "Lembram suas preferências",
    // Account Settings Page
    "settings_title": "Configurações",
    "language_title": "Idioma",
    "language_sub": "Idioma do aplicativo",
    "language_pt": "Português",
    "language_en": "Inglês (English)",
    "notifications_title": "Notificações",
    "notifications_desc_active": "Mensagens Diárias (8h e 20h)",
    "notifications_desc_inactive": "Desativadas",
    "focus_title": "Foco",
    "focus_badge_timer": "Timer de 1 hora",
    "focus_desc_active": "Ativado — toasts normais silenciados para focar na Palavra",
    "focus_desc_inactive": "Desativa toasts normais para focar na Palavra (1h de timer)",
    "focus_time_remaining": "Tempo restante de foco:",
    "focus_renew": "Renovar 1h",
    "focus_turn_off": "Desativar",
    "test_now": "Testar Agora",
    "clock_status": "Status do Relógio:",
    "clock_active": "Ativo",
    "offline_title": "Bíblia Offline",
    "offline_desc_downloading": "Baixando...",
    "offline_desc_active": "Baixada — funciona sem internet",
    "offline_desc_inactive": "Baixar para usar offline",
    "delete_account": "Excluir Minha Conta e Dados",
    "delete_account_desc": "Apagar perfil e atividades permanentemente",
    "sign_out": "Sair da Conta",
    "add_name": "Adicionar nome",
    "your_name": "Seu nome",
    "not_supported": "Não suportado",
    "not_supported_desc": "Seu navegador não suporta notificações.",
    "permission_denied": "Permissão Negada",
    "permission_denied_desc": "Você precisa permitir notificações nas configurações do seu navegador para testar.",
    "notifications_blocked": "Notificações Bloqueadas",
    "notifications_blocked_desc": "Por favor, libere a permissão de notificações nas configurações do site no seu navegador.",
    "test_sent": "Teste enviado! 🔔",
    "test_sent_desc": "Você deve receber uma notificação em instantes.",
    "login_needed": "Faça login para salvar seu progresso e sincronizar seus dados.",
    "enter_account": "Entrar na Conta",
    "create_account": "Criar Conta",
    "deleting_profile": "Carregando...",
    "delete_modal_title": "Excluir Conta",
    "delete_modal_alert": "Alerta: ao excluir sua conta você apagará todos seus dados e não poderá recuperá-los. Além disso, você terá que aguardar um período de 30 dias para poder criar uma nova conta com este mesmo e-mail.",
    "delete_modal_confirm": "Apagar meus dados",
    "delete_modal_cancel": "Cancelar",
    // Two-Factor Authentication (2FA)
    "two_factor_title": "Verificação em Duas Etapas",
    "two_factor_active": "Ativada com Google Authenticator",
    "two_factor_inactive": "Desativada",
    "two_factor_loading": "Carregando...",
    "two_factor_setup_title": "Configurar Verificação em Duas Etapas",
    "two_factor_step_1": "Passo 1 de 3: Escanear QR Code",
    "two_factor_step_1_desc": "Escaneie este QR Code no Google Authenticator ou outro aplicativo TOTP:",
    "two_factor_cant_scan": "Não consegue escanear? Use a chave secreta:",
    "two_factor_copy_key": "Copiar Chave",
    "two_factor_key_copied": "Chave copiada!",
    "two_factor_step_2": "Passo 2 de 3: Códigos de Recuperação",
    "two_factor_step_2_desc": "Guarde estes códigos de backup em um local seguro caso perca acesso ao seu celular:",
    "two_factor_copy_codes": "Copiar Códigos",
    "two_factor_codes_copied": "Códigos copiados!",
    "two_factor_step_3": "Passo 3 de 3: Confirmar Código",
    "two_factor_step_3_desc": "Digite o código de 6 dígitos gerado pelo Google Authenticator para ativar:",
    "two_factor_verify_btn": "Verificar e Ativar 2FA",
    "two_factor_disable_title": "Desativar Verificação em Duas Etapas?",
    "two_factor_disable_desc": "Sua conta ficará menos protegida caso remova a camada extra de segurança do Google Authenticator.",
    "two_factor_disable_confirm": "Confirmar Desativação",
    "two_factor_login_title": "Verificação em 2 Etapas",
    "two_factor_login_desc": "Abra o Google Authenticator e digite o código de 6 dígitos gerado para",
    "two_factor_login_backup_desc": "Digite um dos seus códigos de recuperação (backup) para entrar na conta:",
    "two_factor_login_verify": "Verificar Código",
    "two_factor_login_use_backup": "Usar código de backup de recuperação",
    "two_factor_login_use_totp": "Voltar para o Google Authenticator",
    // Biometrics
    "biometrics_title": "Biometria",
    "biometrics_active": "Ativo (solicita biometria/senha ao abrir)",
    "biometrics_inactive": "Desativada",
    "biometrics_setting_up": "Configurando...",
    "biometrics_pwa_only": "Exclusivo no App (PWA) • Toque para ver",
    "biometrics_pwa_guide_title": "Instale o App para usar Biometria",
    "biometrics_pwa_guide_desc": "O desbloqueio por Face ID, Impressão Digital ou PIN nativo requer o aplicativo instalado no seu celular.",
    "biometrics_pwa_guide_ios": "Como instalar no iPhone (Safari):",
    "biometrics_pwa_guide_ios_desc": "Toque no botão Compartilhar e selecione Adicionar à Tela de Início.",
    "biometrics_pwa_guide_android": "Como instalar no Android (Chrome):",
    "biometrics_pwa_guide_android_desc": "Toque nos 3 pontos do menu e selecione Instalar aplicativo.",
    "biometrics_pwa_guide_btn": "Entendi",
    "biometrics_lock_title": "Aplicativo Bloqueado",
    "biometrics_lock_desc": "Toque para autenticar com Face ID, Touch ID ou PIN do dispositivo.",
    "biometrics_lock_unlock_btn": "Desbloquear com Biometria",
    "biometrics_lock_switch_account": "Entrar com outra conta",
    "biometrics_lock_authenticating": "Autenticando...",
    "biometrics_lock_unlocked": "Desbloqueado com Sucesso",
    // Offline AI
    "no_connection": "Sem Conexão",
    "no_internet_ai_desc": "Você precisa de internet para usar IA. Por favor, verifique sua conexão Wi-Fi ou dados móveis e tente novamente.",
    "try_again": "Tentar novamente",
    "no_internet_dict_desc": "Você precisa de internet para usar o Dicionário com IA",
    "no_internet_dict_sub": "Por favor, reconecte-se e tente novamente.",
    "no_internet_translation_desc": "Você precisa de internet para usar Tradução com IA",
    "no_internet_translation_sub": "O modo Bilíngue requer internet para traduzir dinamicamente os versículos via Inteligência Artificial.",
    "no_internet_create_desc": "Você precisa de internet para usar IA",
    "no_internet_create_sub": "O modo Criar com IA requer uma conexão ativa com a internet para gerar novos fundos baseados em versículos.",
    // Create Mode (Modo Criar)
    "create_title": "Crie Artes e Cartões Bíblicos",
    "create_subtitle": "Personalize o texto, fontes, fundos com IA e baixe em alta resolução para compartilhar.",
    "create_studio_badge": "Estúdio de Criação Bíblica",
    "create_download_art": "Baixar Arte",
    "create_share": "Compartilhar",
    "create_tab_verse": "Versículo",
    "create_tab_bg": "Fundo",
    "create_tab_text": "Texto",
    "create_tab_format": "Formato",
    "create_search_passage": "Buscar Passagem",
    "create_search_placeholder": "Ex: Filipenses 4:13",
    "create_search_placeholder_offline": "Indisponível offline",
    "create_search_btn": "Buscar",
    "create_quick_suggestions": "Sugestões Rápidas:",
    "create_edit_manual": "Editar Texto Manualmente",
    "create_verse_text_label": "Texto do Versículo:",
    "create_text_placeholder": "Digite o texto aqui...",
    "create_ref_label": "Referência Bíblica:",
    "create_ref_placeholder": "Ex: Salmos 23:1",
    "create_bg_themes": "Temas",
    "create_bg_gradient": "Gradiente",
    "create_bg_solid": "Sólida",
    "create_bg_ai": "IA",
    "create_preset_themes": "Temas Pré-definidos",
    "create_elegant_gradients": "Gradientes Elegantes",
    "create_solid_picker_label": "Cor de Fundo Sólida",
    "create_ai_bg_title": "Fundo Inteligente com IA",
    "create_ai_today_count": "hoje",
    "create_ai_choose_style": "Escolha o estilo estético do fundo:",
    "create_ai_describe_scene": "Descreva o cenário bíblico (apenas natureza, proibido pessoas e estátuas):",
    "create_ai_prompt_placeholder": "Ex: Montanhas de Jerusalém ao pôr do sol, Rio Jordão sereno, oliveiras...",
    "create_ai_disclaimer": "O Modo Criar gera exclusivamente paisagens e cenários bíblicos sagrados (sem pessoas ou estátuas gregas/esculturas), ideal para destacar com clareza o versículo sagrado.",
    "create_overlay_darkness": "Escurecimento de Fundo:",
    "create_daily_limit_title": "Limite Diário Atingido",
    "create_daily_limit_desc": "Você atingiu o limite de 3 imagens por dia no Modo Criar. Sua cota recarrega em 12 horas.",
    "create_btn_generate_ai": "Gerar Imagem com IA",
    "create_btn_generating": "Criando imagem no servidor...",
    "create_btn_limit_reached": "Limite diário atingido",
    "create_font_family": "Família Tipográfica",
    "create_font_size": "Tamanho da Fonte",
    "create_text_color": "Cor do Texto (Sobre a Foto)",
    "create_aspect_ratio": "Proporção da Imagem",
    "create_quality_resolution": "Qualidade e Resolução",
    "create_file_format": "Formato de Arquivo",
    "create_save_art": "Salvar",
    "create_share_direct": "Compartilhar Direto",
    "create_preview_title": "Pré-visualização da Arte",
    "create_start_searching_verse": "Busque um versículo para começar",
    "create_load_fail": "Falha no carregamento",
    "create_load_fail_desc": "Erro ao carregar imagem. Tente alterar o estilo ou gerar novamente.",
    "create_format_square": "Quadrado",
    "create_format_story": "Story",
    "create_format_landscape": "Paisagem",
    "create_quality_sd": "720p (SD)",
    "create_quality_sd_desc": "Envio Rápido • 150 DPI",
    "create_quality_hd": "1080p (Full HD)",
    "create_quality_hd_desc": "Recomendado • 300 DPI",
    "create_quality_4k": "4K (Ultra HD)",
    "create_quality_4k_desc": "Máxima Nitidez • 600 DPI",
    "create_pipette": "Pipeta",
    "create_color_palette": "Paleta de Cores Sólidas",
    "create_generating_title": "Gerando Imagem com IA",
    "create_generating_processing": "Processando...",
    "create_connection_needed": "Conexão necessária",
    "create_connection_needed_desc": "A geração de imagens por IA requer internet ativa.",
    // Biblical AI (IA Bíblica)
    "ai_page_title": "IA Bíblica",
    "ai_page_subtitle": "Converse, estude passagens e crie com Inteligência Artificial",
    "ai_new_chat": "Nova Conversa",
    "ai_chat_history": "Histórico de Conversas",
    "ai_search_history": "Pesquisar conversas...",
    "ai_clear_history": "Limpar Histórico",
    "ai_clear_history_confirm_title": "Limpar Todo o Histórico?",
    "ai_clear_history_confirm_desc": "Esta ação apagará todas as suas conversas salvas no dispositivo e no servidor permanentemente.",
    "ai_clear_history_confirm_btn": "Sim, Limpar Tudo",
    "ai_cancel": "Cancelar",
    "ai_mode_chat": "Conversa",
    "ai_mode_learning": "Aprendizado",
    "ai_mode_image": "Gerar Imagem",
    "ai_mode_video": "Gerar Vídeo",
    "ai_mode_music": "Criar Músicas",
    "ai_engine_simple": "IA Simples",
    "ai_engine_complex": "IA Complexa",
    "ai_engine_simple_desc": "Respostas rápidas e diretas",
    "ai_engine_complex_desc": "Estudo teológico aprofundado",
    "ai_placeholder": "Pergunte sobre a Bíblia, peça um estudo ou gere imagens...",
    "ai_placeholder_offline": "IA indisponível sem conexão com a internet",
    "ai_attach_file": "Anexar arquivo",
    "ai_send": "Enviar",
    "ai_stop_generating": "Parar geração",
    "ai_thinking": "Pensando...",
    "ai_copy": "Copiar",
    "ai_copied": "Copiado!",
    "ai_share": "Compartilhar",
    "ai_download": "Baixar Imagem",
    "ai_like": "Útil",
    "ai_dislike": "Não foi útil",
    "ai_retry": "Tentar novamente",
    "ai_daily_limit_reached": "Limite diário atingido",
    "ai_quota_recharge": "Sua cota recarrega em até 12h.",
    "ai_login_required_title": "Faça login para conversar com a IA",
    "ai_login_required_desc": "Faça login para ter acesso completo ao seu assistente bíblico pessoal com inteligência artificial.",
    "ai_login_perk_1": "Conversas teológicas e respostas bíblicas",
    "ai_login_perk_2": "Roteiros, estudos teológicos e louvores",
    "ai_login_perk_3": "Histórico criptografado e seguro",
    "ai_login_btn": "Criar conta / Fazer login",
    "ai_style_cinematic": "Cinematográfico",
    "ai_style_cinematic_desc": "Estilo cinematográfico natural",
    "ai_style_drawing": "Desenho",
    "ai_style_drawing_desc": "Ilustração e desenho artístico",
    "ai_style_photorealism": "Fotorealismo",
    "ai_style_photorealism_desc": "Fotografia realista de alta fidelidade",
    "ai_style_pixel": "Pixel Art",
    "ai_style_pixel_desc": "Arte clássica em pixel art",
    "ai_no_conversations": "Nenhuma conversa iniciada ainda.",
    "ai_filter_all": "Todas",
    "ai_filter_simple": "Simples",
    "ai_filter_complex": "Complexa",
    "ai_filter_image": "Imagens"
  },
  en: {
    // Nav
    "nav_home": "Home",
    "nav_search": "Search",
    "nav_ai": "AI",
    "nav_favorites": "Reactions",
    "nav_devotional": "Devotionals and Plans",
    "nav_devotional_short": "Devotionals",
    "nav_create": "Create",
    "nav_account": "Account",
    // User Role Badges
    "role_admin": "Admin Account",
    "role_beta": "Beta Account",
    "role_standard": "Normal Account",
    // Presentation / Pulpit Mode
    "present": "Present",
    "present_mode": "Presentation Mode",
    "present_desc": "Present verses in full screen (Testing Feature)",
    "present_options": "Presentation Options",
    "present_exit": "Exit Presentation",
    "present_exit_esc": "Exit Presentation (Esc)",
    "present_fullscreen": "Fullscreen (F)",
    "present_exit_fullscreen": "Exit Fullscreen (F)",
    "present_verse_of": "Verse",
    "present_of": "of",
    "present_change_book_chapter": "Change Book or Chapter",
    "present_font_size": "Font Size",
    "present_screen_theme": "Screen Theme",
    "present_theme_app": "App Theme",
    "present_theme_dark": "Obsidian / Pure Black",
    "present_theme_gold": "Noble Gold",
    "present_theme_emerald": "Sacred Emerald",
    "present_select_book_chapter": "Select Book and Chapter",
    "present_select_chapter": "Select Chapter:",
    "present_current_chapter": "Current chapter:",
    "present_prev_verse": "Previous verse",
    "present_next_verse": "Next verse",
    "present_smooth_transition": "Smooth Transition",
    "present_auto_speed": "Auto-Playback Speed",
    // Reader and Bilingual
    "bilingual": "Bilingual",
    "bilingual_translating": "Translating with AI...",
    "bilingual_active": "AI Translation active",
    "bilingual_login_needed": "Please log in to use bilingual mode",
    "bilingual_limit_title": "Bilingual Mode Limit Reached",
    "bilingual_limit_desc": "You have reached the limit of 3 translated chapters per day in free mode. Quota resets in 12 hours.",
    "bilingual_realtime": "Translating verses in real-time (batches of 5)...",
    "bilingual_translating_verse": "Translating verse...",
    // Dictionary
    "dictionary": "Dictionary",
    "dictionary_login_needed": "Please log in to use dictionary",
    "dictionary_ai_badge": "Bible Dictionary AI",
    "dictionary_ai_sub": "AI powered by biblical scholarship",
    "dictionary_analyzing": "Analyzing verse and historical context...",
    "dictionary_limit_title": "Dictionary Limit Reached",
    "dictionary_limit_desc": "You have reached the limit of 3 Dictionary queries per day in free mode. Quota resets in 12 hours.",
    "dict_title": "Bible Dictionary AI",
    "dict_subtitle": "AI powered by biblical scholarship",
    "dict_offline_title": "Offline Mode",
    "dict_offline_desc": "AI Dictionary requires an active internet connection.",
    "dict_analyzing": "Analyzing verse and historical context...",
    "dict_limit_title": "Dictionary Limit Reached",
    "dict_limit_desc": "You have reached the limit of 3 Dictionary queries per day in free mode. Quota resets in 12 hours.",
    // Reader General
    "books": "Books",
    "book_not_found": "Book not found.",
    "save": "Save",
    "cancel": "Cancel",
    "write_note": "Write your note... (max. 1000 characters)",
    "note_placeholder": "Write your note... (max. 1000 characters)",
    "create_image_count": "Create image",
    "create_image": "Create image",
    "share_text": "Share text",
    "offline_mode_title": "Offline Mode",
    "offline_mode_desc": "No connection and no offline data downloaded. To read without internet, download the Bible.",
    "download_offline_bible": "Download Offline Bible",
    "load_more_verses": "Loading more verses incrementally... or click to display more",
    "loading_more_verses": "Loading more verses incrementally... or click to display more",
    "chapter_abbrev": "Ch.",
    "chapter_short": "Ch.",
    // Font Size and Audio Speech Reader
    "font_size_btn": "Font Size",
    "font_size_sm": "Small (14px)",
    "font_size_md": "Medium (16px)",
    "font_size_lg": "Large (18px)",
    "font_size_xl": "Extra Large (22px)",
    "font_size_2xl": "Huge (26px)",
    "audio_reader_btn": "Read Aloud",
    "audio_reader_playing": "Reading Chapter Aloud...",
    "audio_reader_paused": "Audio Paused",
    "audio_reader_stopped": "Audio Reading Stopped",
    "audio_reader_unsupported": "Your browser does not support text-to-speech synthesis (TTS).",
    "audio_verse_label": "Current Verse:",
    "audio_speed_label": "Speed:",
    "maps_biblical_title": "Biblical Maps",
    "maps_biblical_sub": "Geography and Historical Scripture Routes",
    // Home / Index
    "hero_subtitle": "Read the Word, study with Biblical AI, and transform verses into art. All in one place.",
    "created_by": "Created by Mundo Gospel",
    "subscribe": "Subscribe",
    "verse_of_the_day": "Verse of the Day",
    "thousands_verses": "+1,000 Sacred Verses",
    "thousands_verses_sub": "Over 31,000 verses and 66 Holy Books",
    "thousands_verses_desc": "Instant offline navigation, translation comparisons, and study across any chapter in the Bible.",
    "start_reading_genesis": "Start Reading (Genesis 1)",
    "ai_dictionary_title": "Dictionary and Biblical AI",
    "ai_dictionary_sub": "In-Depth Study and Theological AI Dictionary",
    "ai_dictionary_desc": "Clarify historical contexts, original Hebrew/Greek words, and practical applications for each verse.",
    "access_ai": "Access Biblical Artificial Intelligence",
    "create_page_verse": "Create page with this verse",
    "old_testament": "Old Testament",
    "new_testament": "New Testament",
    "chapters_count": "ch.",
    "all_rights_reserved": "© 2026 Biblia Online. All rights reserved.",
    "terms_privacy": "Terms of Use and Privacy Policy",
    // Devotionals and Plans Page
    "devotional_title": "Devotionals and Daily Plans",
    "devotional_subtitle": "Daily meditations and structured reading plans to strengthen your faith each day.",
    "tab_today_devotional": "Today's Devotional",
    "tab_reading_plans": "Reading Plans",
    "tab_biblical_maps": "Biblical Maps",
    "tab_explore_devotionals": "Explore Devotionals",
    "tab_my_favorites": "My Favorites",
    "meditation_of_the_day": "Meditation of the Day",
    "changes_at_midnight": "Changes automatically at midnight",
    "theme_label": "Theme:",
    "reflection_title": "Reflection",
    "today_prayer": "Today's Prayer",
    "copy_devotional": "Copy Devotional",
    "share_devotional": "Share Devotional",
    "copied": "Copied!",
    "copy": "Copy",
    "read_full_reflection": "Read full reflection",
    "collapse_reflection": "Collapse",
    "recommended_prayer": "Recommended Prayer",
    "filter_by_theme": "Filter by Theme",
    "search_devotionals_placeholder": "Search by title, verse, reference or reflection...",
    "showing_devotionals_count": "Showing",
    "of_devotionals": "of",
    "devotionals_available": "available devotionals.",
    "no_devotionals_found": "No devotionals match the search criteria.",
    "clear_search_filters": "Clear search filters",
    "favorited_devotionals": "Favorited Devotionals",
    "favorited_reading_plans": "Favorited Reading Plans",
    "no_favorited_devotionals": "No individual devotionals saved in favorites yet.",
    "no_favorited_plans": "No reading plans saved in favorites yet.",
    "go_to_plan": "Go to Plan",
    "days_unit": "Days",
    "all_categories": "All",
    "plan_active_badge": "Active Plan",
    "plan_duration": "Duration",
    "plan_completed_badge": "Completed!",
    "plan_start_btn": "Start Plan",
    "plan_continue_btn": "Continue Reading",
    "plan_streak": "Streak",
    "plan_days_done": "days completed",
    "plan_day_label": "Day",
    "plan_mark_completed": "Mark as completed",
    "plan_unmark": "Unmark",
    "plan_reflection_placeholder": "What did God speak to your heart today in this passage?",
    "plan_save_reflection": "Save Lesson",
    "plan_reflection_saved": "Lesson saved!",
    // Favorites and Reactions Page
    "reactions_title": "Reactions and Favorites",
    "reactions_subtitle": "Saved verses, highlights, and your personal spiritual notes from the Word.",
    "fav_tab_favorites": "Favorites",
    "fav_tab_markings": "Highlights",
    "fav_tab_notes": "Notes",
    "fav_title_favorites": "Favorite Verses",
    "fav_title_markings": "Highlights",
    "fav_title_notes": "Notes",
    "fav_no_favorites": "No favorite verses yet. Tap the heart icon on any chapter to save your favorite verses.",
    "fav_no_markings": "No highlights yet. Highlight verses during your scripture reading.",
    "fav_no_notes": "No notes yet. Write reflections on any verse.",
    "fav_recommendations": "Recommendations",
    "fav_edit_note": "Edit note",
    "fav_save_note": "Save note",
    "fav_remove": "Remove",
    "fav_verse_copied": "Verse copied successfully",
    // Cookies and LGPD
    "cookie_title": "Privacy and Cookies (LGPD/GDPR)",
    "cookie_desc": "To ensure transparency and compliance, we use cookies to personalize your experience, optimize navigation, and analyze site performance. We respect your rights and give you full control over your privacy settings.",
    "cookie_accept_all": "Accept All",
    "cookie_reject_non_essential": "Reject Non-Essential",
    "cookie_configure": "Configure",
    "cookie_customize": "Customize",
    "cookie_save_preferences": "Save Preferences",
    "cookie_essential": "Essential",
    "cookie_essential_desc": "Required for core functionality",
    "cookie_analytics": "Analytics and Performance",
    "cookie_analytics_desc": "Helps improve our services",
    "cookie_functional": "Functional",
    "cookie_functional_desc": "Remembers your preferences",
    "cookies_title": "Privacy and Cookies (LGPD/GDPR)",
    "cookies_desc": "To ensure transparency and compliance, we use cookies to personalize your experience, optimize navigation, and analyze site performance. We respect your rights and give you full control over your privacy settings.",
    "cookies_accept_all": "Accept All",
    "cookies_reject_non_essential": "Reject Non-Essential",
    "cookies_configure": "Configure",
    "cookies_customize": "Customize",
    "cookies_save": "Save Preferences",
    "cookies_essential": "Essential",
    "cookies_essential_desc": "Required for core functionality",
    "cookies_analytics": "Analytics and Performance",
    "cookies_analytics_desc": "Helps improve our services",
    "cookies_personalization": "Functional",
    "cookies_personalization_desc": "Remembers your preferences",
    // Account Settings Page
    "settings_title": "Settings",
    "language_title": "Language",
    "language_sub": "Application language",
    "language_pt": "Português",
    "language_en": "Inglês (English)",
    "notifications_title": "Notifications",
    "notifications_desc_active": "Daily Messages (8am and 8pm)",
    "notifications_desc_inactive": "Disabled",
    "focus_title": "Focus",
    "focus_badge_timer": "1-hour timer",
    "focus_desc_active": "Active — normal toasts silenced to focus on the Word",
    "focus_desc_inactive": "Disables normal toasts to focus on the Word (1h timer)",
    "focus_time_remaining": "Focus time remaining:",
    "focus_renew": "Renew 1h",
    "focus_turn_off": "Turn Off",
    "test_now": "Test Now",
    "clock_status": "Clock Status:",
    "clock_active": "Active",
    "offline_title": "Offline Bible",
    "offline_desc_downloading": "Downloading...",
    "offline_desc_active": "Downloaded — works without internet",
    "offline_desc_inactive": "Download to use offline",
    "delete_account": "Delete My Account and Data",
    "delete_account_desc": "Permanently delete profile and activities",
    "sign_out": "Sign Out",
    "add_name": "Add name",
    "your_name": "Your name",
    "not_supported": "Not supported",
    "not_supported_desc": "Your browser does not support notifications.",
    "permission_denied": "Permission Denied",
    "permission_denied_desc": "You need to allow notifications in your browser settings to test.",
    "notifications_blocked": "Notifications Blocked",
    "notifications_blocked_desc": "Please enable notification permission in your browser's site settings.",
    "test_sent": "Test sent! 🔔",
    "test_sent_desc": "You should receive a notification in a moment.",
    "login_needed": "Log in to save your progress and sync your data.",
    "enter_account": "Sign In",
    "create_account": "Create Account",
    "deleting_profile": "Loading...",
    "delete_modal_title": "Delete Account",
    "delete_modal_alert": "Warning: deleting your account will erase all your data and cannot be recovered. Additionally, you will have to wait for a period of 30 days before being able to create a new account with this same email.",
    "delete_modal_confirm": "Delete my data",
    "delete_modal_cancel": "Cancel",
    // Two-Factor Authentication (2FA)
    "two_factor_title": "Two-Factor Authentication",
    "two_factor_active": "Enabled with Google Authenticator",
    "two_factor_inactive": "Disabled",
    "two_factor_loading": "Loading...",
    "two_factor_setup_title": "Set up Two-Factor Authentication",
    "two_factor_step_1": "Step 1 of 3: Scan QR Code",
    "two_factor_step_1_desc": "Scan this QR Code in Google Authenticator or another TOTP app:",
    "two_factor_cant_scan": "Can't scan? Use the secret key:",
    "two_factor_copy_key": "Copy Key",
    "two_factor_key_copied": "Key copied!",
    "two_factor_step_2": "Step 2 of 3: Backup Codes",
    "two_factor_step_2_desc": "Save these backup codes in a safe place in case you lose access to your phone:",
    "two_factor_copy_codes": "Copy Codes",
    "two_factor_codes_copied": "Codes copied!",
    "two_factor_step_3": "Step 3 of 3: Confirm Code",
    "two_factor_step_3_desc": "Enter the 6-digit code generated by Google Authenticator to enable:",
    "two_factor_verify_btn": "Verify and Enable 2FA",
    "two_factor_disable_title": "Disable Two-Factor Authentication?",
    "two_factor_disable_desc": "Your account will be less secure if you remove the extra security layer of Google Authenticator.",
    "two_factor_disable_confirm": "Confirm Disabling",
    "two_factor_login_title": "2-Step Verification",
    "two_factor_login_desc": "Open Google Authenticator and enter the 6-digit code generated for",
    "two_factor_login_backup_desc": "Enter one of your backup recovery codes to log into your account:",
    "two_factor_login_verify": "Verify Code",
    "two_factor_login_use_backup": "Use a backup recovery code",
    "two_factor_login_use_totp": "Back to Google Authenticator",
    // Biometrics
    "biometrics_title": "Biometrics",
    "biometrics_active": "Active (prompts biometrics/PIN on open)",
    "biometrics_inactive": "Disabled",
    "biometrics_setting_up": "Setting up...",
    "biometrics_pwa_only": "Exclusive in App (PWA) • Tap to view",
    "biometrics_pwa_guide_title": "Install the App to use Biometrics",
    "biometrics_pwa_guide_desc": "Unlocking with Face ID, Fingerprint, or native PIN requires the app installed on your device.",
    "biometrics_pwa_guide_ios": "How to install on iPhone (Safari):",
    "biometrics_pwa_guide_ios_desc": "Tap the Share button and select Add to Home Screen.",
    "biometrics_pwa_guide_android": "How to install on Android (Chrome):",
    "biometrics_pwa_guide_android_desc": "Tap the 3-dot menu and select Install App.",
    "biometrics_pwa_guide_btn": "Got it",
    "biometrics_lock_title": "App Locked",
    "biometrics_lock_desc": "Tap to authenticate with Face ID, Touch ID, or device PIN.",
    "biometrics_lock_unlock_btn": "Unlock with Biometrics",
    "biometrics_lock_switch_account": "Sign in with another account",
    "biometrics_lock_authenticating": "Authenticating...",
    "biometrics_lock_unlocked": "Unlocked Successfully",
    // Offline AI
    "no_connection": "No Connection",
    "no_internet_ai_desc": "You need internet to use AI. Please check your Wi-Fi or mobile data connection and try again.",
    "try_again": "Try again",
    "no_internet_dict_desc": "You need internet to use Bible Dictionary AI",
    "no_internet_dict_sub": "Please reconnect and try again.",
    "no_internet_translation_desc": "You need internet to use AI Translation",
    "no_internet_translation_sub": "Bilingual mode requires internet to dynamically translate verses via Artificial Intelligence.",
    "no_internet_create_desc": "You need internet to use AI",
    "no_internet_create_sub": "Create with AI mode requires an active internet connection to generate new verse-based backgrounds.",
    // Create Mode (Modo Criar)
    "create_title": "Create Biblical Art and Cards",
    "create_subtitle": "Customize text, fonts, AI backgrounds, and download in high resolution to share.",
    "create_studio_badge": "Biblical Creation Studio",
    "create_download_art": "Download Art",
    "create_share": "Share",
    "create_tab_verse": "Verse",
    "create_tab_bg": "Background",
    "create_tab_text": "Typography",
    "create_tab_format": "Format",
    "create_search_passage": "Search Passage",
    "create_search_placeholder": "E.g.: Philippians 4:13",
    "create_search_placeholder_offline": "Unavailable offline",
    "create_search_btn": "Search",
    "create_quick_suggestions": "Quick Suggestions:",
    "create_edit_manual": "Edit Text Manually",
    "create_verse_text_label": "Verse Text:",
    "create_text_placeholder": "Enter verse text here...",
    "create_ref_label": "Scripture Reference:",
    "create_ref_placeholder": "E.g.: Psalms 23:1",
    "create_bg_themes": "Themes",
    "create_bg_gradient": "Gradient",
    "create_bg_solid": "Solid Color",
    "create_bg_ai": "AI",
    "create_preset_themes": "Preset Themes",
    "create_elegant_gradients": "Elegant Gradients",
    "create_solid_picker_label": "Solid Background Color",
    "create_ai_bg_title": "Smart AI Background",
    "create_ai_today_count": "today",
    "create_ai_choose_style": "Choose the aesthetic background style:",
    "create_ai_describe_scene": "Describe the biblical scenery (nature only, no people or statues):",
    "create_ai_prompt_placeholder": "E.g.: Mountains of Jerusalem at sunset, serene Jordan River, olive trees...",
    "create_ai_disclaimer": "Create Mode exclusively generates sacred biblical landscapes and scenery (without people or statues/sculptures), ideal for clearly highlighting holy scripture.",
    "create_overlay_darkness": "Background Dimming:",
    "create_daily_limit_title": "Daily Limit Reached",
    "create_daily_limit_desc": "You reached the limit of 3 images per day in Create Mode. Your quota resets in 12 hours.",
    "create_btn_generate_ai": "Generate AI Background",
    "create_btn_generating": "Creating image on server...",
    "create_btn_limit_reached": "Daily limit reached",
    "create_font_family": "Font Family",
    "create_font_size": "Font Size",
    "create_text_color": "Text Color (Over Image)",
    "create_aspect_ratio": "Image Aspect Ratio",
    "create_quality_resolution": "Quality and Resolution",
    "create_file_format": "File Format",
    "create_save_art": "Save",
    "create_share_direct": "Share Directly",
    "create_preview_title": "Art Preview",
    "create_start_searching_verse": "Search a verse to get started",
    "create_load_fail": "Failed to load",
    "create_load_fail_desc": "Error loading image. Try changing the style or generating again.",
    "create_format_square": "Square",
    "create_format_story": "Story",
    "create_format_landscape": "Landscape",
    "create_quality_sd": "720p (SD)",
    "create_quality_sd_desc": "Fast Upload • 150 DPI",
    "create_quality_hd": "1080p (Full HD)",
    "create_quality_hd_desc": "Recommended • 300 DPI",
    "create_quality_4k": "4K (Ultra HD)",
    "create_quality_4k_desc": "Maximum Crispness • 600 DPI",
    "create_pipette": "Eyedropper",
    "create_color_palette": "Solid Color Palette",
    "create_generating_title": "Generating Image with AI",
    "create_generating_processing": "Processing...",
    "create_connection_needed": "Connection needed",
    "create_connection_needed_desc": "AI image generation requires an active internet connection.",
    // Biblical AI (IA Bíblica)
    "ai_page_title": "Biblical AI",
    "ai_page_subtitle": "Chat, study scriptures, and create with Artificial Intelligence",
    "ai_new_chat": "New Chat",
    "ai_chat_history": "Chat History",
    "ai_search_history": "Search chats...",
    "ai_clear_history": "Clear History",
    "ai_clear_history_confirm_title": "Clear All History?",
    "ai_clear_history_confirm_desc": "This action will permanently delete all your saved conversations on this device and on the server.",
    "ai_clear_history_confirm_btn": "Yes, Clear All",
    "ai_cancel": "Cancel",
    "ai_mode_chat": "Chat",
    "ai_mode_learning": "Learning",
    "ai_mode_image": "Generate Image",
    "ai_mode_video": "Generate Video",
    "ai_mode_music": "Create Music",
    "ai_engine_simple": "Simple AI",
    "ai_engine_complex": "Complex AI",
    "ai_engine_simple_desc": "Fast and direct answers",
    "ai_engine_complex_desc": "In-depth theological study",
    "ai_placeholder": "Ask anything about the Bible, request a study, or generate images...",
    "ai_placeholder_offline": "AI unavailable without an internet connection",
    "ai_attach_file": "Attach file",
    "ai_send": "Send",
    "ai_stop_generating": "Stop generating",
    "ai_thinking": "Thinking...",
    "ai_copy": "Copy",
    "ai_copied": "Copied!",
    "ai_share": "Share",
    "ai_download": "Download Image",
    "ai_like": "Helpful",
    "ai_dislike": "Not helpful",
    "ai_retry": "Try again",
    "ai_daily_limit_reached": "Daily limit reached",
    "ai_quota_recharge": "Your quota resets in up to 12 hours.",
    "ai_login_required_title": "Sign in to chat with AI",
    "ai_login_required_desc": "Sign in to get full access to your personal biblical assistant powered by artificial intelligence.",
    "ai_login_perk_1": "Theological conversations and biblical answers",
    "ai_login_perk_2": "Scripts, theological studies, and worship songs",
    "ai_login_perk_3": "Encrypted and secure history",
    "ai_login_btn": "Create Account / Sign In",
    "ai_style_cinematic": "Cinematic",
    "ai_style_cinematic_desc": "Natural cinematic style",
    "ai_style_drawing": "Drawing",
    "ai_style_drawing_desc": "Artistic illustration and drawing",
    "ai_style_photorealism": "Photorealism",
    "ai_style_photorealism_desc": "High-fidelity realistic photography",
    "ai_style_pixel": "Pixel Art",
    "ai_style_pixel_desc": "Classic pixel art style",
    "ai_no_conversations": "No conversations started yet.",
    "ai_filter_all": "All",
    "ai_filter_simple": "Simple",
    "ai_filter_complex": "Complex",
    "ai_filter_image": "Images"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "pt",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved === "en" || saved === "pt") ? saved : "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["pt"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
