// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// We use 127.0.0.1 as a fallback to avoid DNS lookup failures if vars are missing
const SUPABASE_URL = (envUrl && envUrl.startsWith('http')) ? envUrl : 'http://127.0.0.1';

if (!envUrl || !envUrl.startsWith('http')) {
  console.warn("Supabase URL is not configured. Some features (Auth, AI History, Realtime) will fail with 'Failed to fetch'. Set VITE_SUPABASE_URL in Secrets.");
}

if (envUrl && !envUrl.startsWith('http')) {
  console.error("The provided Supabase URL does not start with 'http'. It looks like you might have accidentally copied the SHA256 digest instead of the actual URL.");
}

// Interceptor opcional ou log para debug de rede
if (import.meta.env.DEV) {
  console.log("Supabase URL:", SUPABASE_URL);
}

const SUPABASE_PUBLISHABLE_KEY = envKey || 'YOUR_SUPABASE_ANON_KEY';


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Guard session against "Invalid Refresh Token" crash loop
const originalGetSession = supabase.auth.getSession.bind(supabase.auth);
const originalGetUser = supabase.auth.getUser.bind(supabase.auth);

const clearStaleSession = () => {
  console.warn("Stale or invalid Supabase session detected. Automatically cleaning up...");
  try {
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
       const key = localStorage.key(i);
       if (key && (key.startsWith('sb-') || key.includes('supabase.auth.token') || key === 'bible-google-user')) {
         keysToRemove.push(key);
       }
    }
    keysToRemove.forEach(k => localStorage.removeItem(k));
    localStorage.setItem('auth-sync-logout', Date.now().toString());
    window.dispatchEvent(new Event('auth-sync-logout-local'));
  } catch (e) {
    console.error("Failed to clean up stale localStorage keys:", e);
  }
};

const isAuthRefreshError = (error: any) => {
  if (!error) return false;
  const errMsg = error.message || String(error);
  return (
    errMsg.includes("Refresh Token Not Found") ||
    errMsg.includes("invalid_grant") ||
    errMsg.includes("refresh_token_not_found") ||
    errMsg.includes("Invalid Refresh Token") ||
    errMsg.includes("session_not_found") ||
    error.status === 400 ||
    error.status === 401
  );
};

supabase.auth.getSession = async () => {
  try {
    const res = await originalGetSession();
    if (res.error && isAuthRefreshError(res.error)) {
      clearStaleSession();
      return { data: { session: null }, error: null };
    }
    return res;
  } catch (err) {
    if (isAuthRefreshError(err)) {
      clearStaleSession();
      return { data: { session: null }, error: null };
    }
    throw err;
  }
};

supabase.auth.getUser = async (jwt?: string) => {
  try {
    const res = await originalGetUser(jwt);
    if (res.error && isAuthRefreshError(res.error)) {
      clearStaleSession();
      return { data: { user: null }, error: null };
    }
    return res;
  } catch (err) {
    if (isAuthRefreshError(err)) {
      clearStaleSession();
      return { data: { user: null }, error: null };
    }
    throw err;
  }
};