// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

export const isSupabaseConfigured = Boolean(
  envUrl &&
  typeof envUrl === 'string' &&
  envUrl.startsWith('http') &&
  !envUrl.includes('127.0.0.1') &&
  envKey &&
  typeof envKey === 'string' &&
  !envKey.includes('YOUR_SUPABASE')
);

// We use 127.0.0.1 as a fallback to avoid DNS lookup failures if vars are missing
const SUPABASE_URL = (envUrl && typeof envUrl === 'string' && envUrl.startsWith('http')) ? envUrl : 'http://127.0.0.1';

if (!isSupabaseConfigured) {
  console.warn("Supabase URL is not configured. Safe mock fallback active to prevent 'Failed to fetch'. Set VITE_SUPABASE_URL in Secrets.");
}

const SUPABASE_PUBLISHABLE_KEY = envKey || 'YOUR_SUPABASE_ANON_KEY';

// In-memory queue-based lock to prevent deadlocks from Navigator LockManager in iframes and multi-tab environments
const inMemoryAuthLocks = new Map<string, Promise<any>>();

const safeAuthLock = async <R>(name: string, acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
  const previous = inMemoryAuthLocks.get(name) ?? Promise.resolve();

  let release: () => void = () => {};
  const current = new Promise<void>((resolve) => {
    release = resolve;
  });

  inMemoryAuthLocks.set(name, previous.then(() => current, () => current));

  let timeoutId: any = null;
  const timeoutPromise = acquireTimeout > 0
    ? new Promise<never>((_, reject) => {
        timeoutId = setTimeout(() => {
          reject(new Error(`Acquiring lock "${name}" timed out waiting ${acquireTimeout}ms`));
        }, Math.min(acquireTimeout, 3000));
      })
    : null;

  try {
    if (timeoutPromise) {
      await Promise.race([previous.catch(() => {}), timeoutPromise]);
    } else {
      await previous.catch(() => {});
    }
    return await fn();
  } catch (err: any) {
    // Se o lock expirar, executa a operação diretamente para não travar a autenticação do usuário
    if (err?.message?.includes("timed out") || err?.name === "AbortError") {
      console.warn(`[Supabase Lock] Aviso de concorrência para "${name}", executando diretamente com segurança.`);
      return await fn();
    }
    throw err;
  } finally {
    if (timeoutId) clearTimeout(timeoutId);
    release();
    if (inMemoryAuthLocks.get(name) === current) {
      inMemoryAuthLocks.delete(name);
    }
  }
};

// Custom safe fetch to intercept unconfigured endpoints or catch network blips
const safeSupabaseFetch: typeof fetch = async (input, init) => {
  const urlStr = typeof input === 'string' ? input : (input instanceof Request ? input.url : String(input));
  
  if (!isSupabaseConfigured || urlStr.includes('127.0.0.1')) {
    const isAuth = urlStr.includes('/auth/v1');
    const body = isAuth ? JSON.stringify({ user: null, session: null }) : JSON.stringify([]);
    return new Response(body, {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });
  }

  try {
    return await fetch(input, init);
  } catch (err: any) {
    const msg = String(err?.message || err).toLowerCase();
    if (msg.includes('failed to fetch') || msg.includes('networkerror') || msg.includes('aborted') || msg.includes('load failed')) {
      console.warn('[Supabase Safe Fetch] Rede instável ou servidor indisponível:', err?.message || err);
      const isAuth = urlStr.includes('/auth/v1');
      const body = isAuth ? JSON.stringify({ user: null, session: null }) : JSON.stringify([]);
      return new Response(body, {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });
    }
    throw err;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: isSupabaseConfigured,
    autoRefreshToken: isSupabaseConfigured,
    lock: safeAuthLock,
  },
  global: {
    fetch: safeSupabaseFetch,
  }
});

// Guard session against "Invalid Refresh Token" crash loop
const originalGetSession = supabase.auth.getSession.bind(supabase.auth);
const originalGetUser = supabase.auth.getUser.bind(supabase.auth);

export const isLockTimeoutError = (error: any): boolean => {
  if (!error) return false;
  let str = '';
  if (typeof error === 'string') {
    str = error;
  } else if (typeof error === 'object') {
    str = [error.message, error.error_description, error.error, error.msg, error.name].filter(Boolean).join(' ');
  } else {
    str = String(error);
  }
  const lowered = str.toLowerCase();
  return (
    lowered.includes("lockmanager") ||
    lowered.includes("navigatorlock") ||
    lowered.includes("lock:sb-") ||
    (lowered.includes("lock") && lowered.includes("timed out waiting"))
  );
};

export const isAuthRefreshError = (error: any) => {
  if (!error) return false;
  
  let str = '';
  if (typeof error === 'string') {
    str = error;
  } else if (typeof error === 'object') {
    str = [
      error.message,
      error.error_description,
      error.error,
      error.msg,
      error.name,
      JSON.stringify(error)
    ].filter(Boolean).join(' ');
  } else {
    str = String(error);
  }
  
  const lowered = str.toLowerCase();
  
  return (
    lowered.includes("refresh token") ||
    lowered.includes("invalid_grant") ||
    lowered.includes("refresh_token_not_found") ||
    lowered.includes("invalid refresh token") ||
    lowered.includes("session_not_found") ||
    lowered.includes("token not found") ||
    lowered.includes("user_not_found") ||
    lowered.includes("jwt expired") ||
    lowered.includes("failed to fetch") ||
    lowered.includes("networkerror") ||
    lowered.includes("lockmanager") ||
    lowered.includes("navigatorlock") ||
    lowered.includes("lock:sb-") ||
    (lowered.includes("lock") && lowered.includes("timed out waiting")) ||
    error?.status === 400 ||
    error?.status === 401
  );
};

export const clearStaleSession = () => {
  console.warn("Stale or invalid Supabase session detected. Automatically cleaning up...");
  try {
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
       const key = localStorage.key(i);
       if (key && (key.startsWith('sb-') || key.includes('supabase.auth.token') || key === 'bible-google-user')) {
         keysToRemove.push(key);
       }
    }
    keysToRemove.forEach(k => localStorage.removeItem(k));
    localStorage.setItem('auth-sync-logout', Date.now().toString());
    window.dispatchEvent(new Event('auth-sync-logout-local'));
  } catch (e) {
    console.error("Failed to clean up stale localStorage keys:", e);
  }
};

supabase.auth.getSession = async () => {
  if (!isSupabaseConfigured) {
    return { data: { session: null }, error: null };
  }
  try {
    const res = await originalGetSession();
    if (res.error) {
      if (isLockTimeoutError(res.error)) {
        console.warn("[Supabase] Lock de autenticação ignorado com segurança em getSession:", res.error);
        return { data: { session: null }, error: null };
      }
      if (isAuthRefreshError(res.error)) {
        clearStaleSession();
        return { data: { session: null }, error: null };
      }
    }
    return res;
  } catch (err) {
    if (isLockTimeoutError(err)) {
      console.warn("[Supabase] Exceção de lock capturada com segurança em getSession:", err);
      return { data: { session: null }, error: null };
    }
    if (isAuthRefreshError(err)) {
      clearStaleSession();
      return { data: { session: null }, error: null };
    }
    return { data: { session: null }, error: null };
  }
};

supabase.auth.getUser = async (jwt?: string) => {
  if (!isSupabaseConfigured) {
    return { data: { user: null }, error: null };
  }
  try {
    const res = await originalGetUser(jwt);
    if (res.error) {
      if (isLockTimeoutError(res.error)) {
        console.warn("[Supabase] Lock de autenticação ignorado com segurança em getUser:", res.error);
        return { data: { user: null }, error: null };
      }
      if (isAuthRefreshError(res.error)) {
        clearStaleSession();
        return { data: { user: null }, error: null };
      }
    }
    return res;
  } catch (err) {
    if (isLockTimeoutError(err)) {
      console.warn("[Supabase] Exceção de lock capturada com segurança em getUser:", err);
      return { data: { user: null }, error: null };
    }
    if (isAuthRefreshError(err)) {
      clearStaleSession();
      return { data: { user: null }, error: null };
    }
    return { data: { user: null }, error: null };
  }
};

if (typeof window !== 'undefined') {
  window.addEventListener('unhandledrejection', (event) => {
    const reasonStr = String(event.reason?.message || event.reason || '').toLowerCase();
    if (
      isAuthRefreshError(event.reason) ||
      isLockTimeoutError(event.reason) ||
      reasonStr.includes('failed to fetch') ||
      reasonStr.includes('networkerror') ||
      reasonStr.includes('lockmanager') ||
      reasonStr.includes('navigatorlock') ||
      reasonStr.includes('lock:sb-') ||
      (reasonStr.includes('lock') && reasonStr.includes('timed out waiting'))
    ) {
      console.warn("Intercepted unhandled network/auth/lock rejection:", event.reason);
      if (isAuthRefreshError(event.reason) && !reasonStr.includes('failed to fetch') && !isLockTimeoutError(event.reason)) {
        clearStaleSession();
      }
      event.preventDefault();
    }
  });

  window.addEventListener('error', (event) => {
    const errStr = String(event.error?.message || event.message || '').toLowerCase();
    if (
      isAuthRefreshError(event.error) ||
      isLockTimeoutError(event.error) ||
      errStr.includes('failed to fetch') ||
      errStr.includes('networkerror') ||
      errStr.includes('lockmanager') ||
      errStr.includes('navigatorlock') ||
      errStr.includes('lock:sb-') ||
      (errStr.includes('lock') && errStr.includes('timed out waiting'))
    ) {
      console.warn("Intercepted global network/auth/lock error:", event.error || event.message);
      if (isAuthRefreshError(event.error) && !errStr.includes('failed to fetch') && !isLockTimeoutError(event.error)) {
        clearStaleSession();
      }
      event.preventDefault();
    }
  });
}